# Site settings
name: Basement
title: Basement
description: ""
baseurl: "/basement"

# Build settings
markdown: kramdown
permalinks: pretty

# Sass settings
sass:
  sass_dir: _sass
  style: :compressed
