# Site settings
name: CSS Workshop
title: CSS Workshop
description: ""
baseurl: "/basement"

# Build settings
markdown: kramdown
permalinks: pretty

# Sass settings
sass:
  sass_dir: _sass
  style: :compressed
